install:
- wget --user $docencia_ac_username --password $docencia_ac_password http://docencia.ac.upc.edu/FIB/grau/PEC/Protegido/Documentacion/eines-sisa-64BITS.tgz
- tar -xf eines-sisa-64BITS.tgz
- export PATH=$PATH:$(pwd)/eines-sisa/bin
script:
- chmod +x ./compile_to_hex.sh
- "./compile_to_hex.sh"
before_deploy:
- rm -rf eines-sisa*
- git config --local user.name "Marc43"
- git config --local user.email "marcdominguezr@gmail.com"
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  overwrite: true
  api_key:
    secure: Il6+gJR8I0I35hGaxO33VJeBO/4oc7RzGCoxpDHuw0STlpi9EQTfYfnclpnkREkyb3Br80mts3eRu3y9Pce+1fbJnpDrexs9oSrxd96dtXx8UghBzlGmg5Z2spzDPndYt3091d/w9KcbTFfFLeNgUtZo7en3TqUg6pT7p/4vygbrwVGwAX3ZYN0bHje3djLKadDPTO4/ce2fApt7x5FF60xCbeeLfesYdem0ILcpEljjiRW207ITozAJmXooTr2Rw49GxmDmCLtEPNjaUTul9+PIYWnJMmC6MkpHuL7e7hUnIJ9GWm5A4rKu4xuUK0LFD15VzJSGPCkTVcCTBBp2Sz7CZCc9Gro/hnxGL5ruFjbsNid1g1Jxk+dAG72MKcxwGS68nrgu6SBoMVhy+tDWD0vYnfmpc/YCIkgALS7M7iX52t0CG71M4J1Nck9ztQVz/ovAE/9+Rwcsmcr3m3A8HAp7N0SRG4A57koR64h01K9IvhBqvXBrZgR7pAYg8R7kOzHb5wkMCKFscwTPcFoaxBFIdCDuz4LUE3ZZCcp3M9pfRWklu3NTE3kxr1eZqVIpJ1QwiUXCxXe5jY9dG9pCFgxNrRLiI0pfDtN8jU1Bwn9QIdM7b7Yq+C79O0z+RhimTSkRJV9DkHyw/CTibYfL0zouLIWFOdCD/8Tkpt9evJA=
  file: hex/*
  skip_cleanup: true
  on:
    repo: Marc43/sisa_hexbuilder
    branches:
        only:
         - master
  script: deploy.sh
